// Re-export maintenance types from the canonical models module.
export {
  CaseStatus,
  FaultType,
  FaultyEntityStatus,
  ResolutionType,
  ActionType,
  ActionOutcome,
  DeliveryType,
  DeliveryStatus,
  EntityType,
  type MaintenanceCase,
  type FaultyEntity,
  type MaintenanceAction,
  type MaintenanceDelivery,
  type CreateMaintenanceCasePayload,
  type UpdateMaintenanceCasePayload,
  type CreateFaultyEntityPayload,
  type UpdateFaultyEntityPayload,
  type CreateMaintenanceActionPayload,
  type UpdateMaintenanceActionPayload,
  type CreateMaintenanceDeliveryPayload,
  type UpdateMaintenanceDeliveryPayload,
  type EntityLookupNode,
  type EntityLookupResponse,
  type SuspectChildrenPayload,
  type ConfirmFaultPayload,
} from '@/lib/models';
